version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
  # We dont need to expose any port since both services will be running in 
  # same bridge network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1" # 1 partition and 1 replica

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb

volumes:
  db-data:
    external:
      name: db-data
  mongo-config:
    external:
      name: mongo-config
