version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
  # We dont need to expose any port since both services will be running in 
  # same bridge network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    hostname: kafkaIP
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafkaIP #172.17.0.1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1" # 1 partition and 1 replica

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
    - mongodb-data:/data/db
    - mongodb-config:/data/configdb

volumes:
  mongodb-data:
    external: true
  mongodb-config:
    external:
      name: mongodb-config
