version: '3.5'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.13/data
      - zookeeper-conf:/opt/zookeeper-3.4.13/conf
  # We dont need to expose any port since both services will be running in 
  # same bridge network

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092, OUTSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1" # 1 partition and 1 replica
    volumes:
      - kafka:/kafka

volumes:
  zookeeper-data:
    external:
      name: zookeeper-data
  zookeeper-conf:
    external:
      name: zookeeper-conf
  kafka:
    external:
      name: kafka